package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, December 15, 2016 4:00:10 PM EET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
